### ISSUE TITLE
Exception durch Wetter API

### ISSUE THREAD

**Issue by HellMar** [Acer54/Webradio_v2#39]
Aktuell scheint es wieder ein Problem mit der Wetter API von weather.com zu geben wie seinerzeit in #9. 

```
Oct  2 12:55:46 raspberrypi sudo[986]: INFO:webradio:Start Update-Cycle for Standby-Screensaver
Oct  2 12:55:47 raspberrypi sudo[986]: 2019-10-02 12:55:46,993 - ERROR - webradio.py - excepthook - Uncaught exception
Oct  2 12:55:47 raspberrypi sudo[986]: Traceback (most recent call last):
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/webradio.py", line 4259, in <module>
Oct  2 12:55:47 raspberrypi sudo[986]:     mainwindow.startup_actions()
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/webradio.py", line 1023, in startup_actions
Oct  2 12:55:47 raspberrypi sudo[986]:     __define_additional_widgets(self)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/webradio.py", line 509, in __define_additional_widgets
Oct  2 12:55:47 raspberrypi sudo[986]:     self)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/lib/screensaver.py", line 44, in __init__
Oct  2 12:55:47 raspberrypi sudo[986]:     self.startUpdate()  # start counters to periodically update conditions
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/lib/screensaver.py", line 153, in startUpdate
Oct  2 12:55:47 raspberrypi sudo[986]:     self.updateWeather() # initially make a call to the API to get the current condition
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/lib/screensaver.py", line 173, in updateWeather
Oct  2 12:55:47 raspberrypi sudo[986]:     temp_condition = weather.get_weather_from_weather_com(location_ID)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/opt/webradio/lib/pyqapi.py", line 112, in get_weather_from_weather_com
Oct  2 12:55:47 raspberrypi sudo[986]:     dom = minidom.parseString(xml_response)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
Oct  2 12:55:47 raspberrypi sudo[986]:     return expatbuilder.parseString(string)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
Oct  2 12:55:47 raspberrypi sudo[986]:     return builder.parseString(string)
Oct  2 12:55:47 raspberrypi sudo[986]:   File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
Oct  2 12:55:47 raspberrypi sudo[986]:     parser.Parse(string, True)
Oct  2 12:55:47 raspberrypi sudo[986]: ExpatError: no element found: line 1, column 1
```
auskommentieren von self.updateWeather() brachte auch hier erstmal Besserung. 
Vlt könnte man die exception ja irgendwie abfangen damit Notfalls ein Start auch ohne Wetter möglich ist.

**Comment by Acer54** [comment]
Hallo @HellMar , gerade wollte ich heute zu debuggen beginnen. Anfangs konnte ich den Fehler auch nachvollziehen, aber mittlerweile scheint die API wieder sauber zu arbeiten und der Webradio funktioniert wieder.
Du hast aber natürlich Recht, dass eine Fehlfunktion der API eines Online-Dienstes nicht den Start des Webradios unterbinden sollte.
Dies werde ich in der nächsten Version berücksichtigen!

**Comment by HiranChaudhuri** [comment]
Ich habe die Methode bei mir mal geändert. Wenn das Wetter nicht verfügbar ist, wird es ausgeblendet. Wenn es dann (evtl später) wieder geladen werden kann, wird es wieder eingeblendet.

```
    def updateWeather(self):
        '''
        This function is called by a QTimer with 5 min. interval,
        Updates the weather-icon and the temperature
        '''
        logger.debug("updateWeather()")
        location_ID = global_vars.configuration.get("GENERAL").get("weather_locationid")
        try:
            if location_ID is None:
                return   #return if no location ID can be loaded...
            temp_condition = weather.get_weather_from_weather_com(location_ID)
            self.lbl_weather_icon.setPicturePath(os.path.join(self.cwd, "res/weather/icon",
                                                              temp_condition['current_conditions']['icon'], "static"))
    
            self.lbl_temperature.setText(temp_condition['current_conditions']['temperature']+QString.fromUtf8("°C"))
            self.lbl_weather_icon.setVisible(True)
            self.lbl_temperature.setVisible(True)
        except Exception as e:
            logger.exception("Could not get weather for location %s", location_ID)
            self.lbl_weather_icon.setVisible(False)
            self.lbl_temperature.setVisible(False)

```

**Comment by Acer54** [comment]
Hi Hiran, Gute Idee! Das übernehme ich mal so. :+1:  Konntest du schon testen?

**Comment by HiranChaudhuri** [comment]
Nein, ich bin am testen von einem ganzen Haufen meiner Änderungen.
Gerade migriere ich auf Python3/Qt5....

Den Code oben habe ich nur aus dem Traceback und der Codeanalyse abgeleitet. Dennoch bin ich zuversichtlich, dass er stimmt.

**Comment by Acer54** [comment]
Übernommen in 0.3.9 (Released am 24.10.2019)
