### ISSUE TITLE
I want to translate in romanian

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#43]
I'm newby in everything. How I do. Is same file with all words? I want to do that. Help me to do.

**Comment by Acer54** [comment]
Thanks for your support in translations!
Here is a brief description how you can translate webradio-py
Under Linux:
(1) Install "qt4-dev-tools" with "sudo apt-get install qt4-dev-tools"  or [click here](apt://qt4-dev-tools)

Under Windows/Mac:
(1) Install Qt-Linguist from [here](https://github.com/lelegard/qtlinguist-installers/releases)

(2) download and save the translation file [local_ro.ts](https://github.com/Acer54/Webradio_v2/raw/master/opt/webradio/locale/local_ro.ts)
(3) Open "Qt4-Linguist" from your dashboard or unter " Development -> Translation -> Qt 4 Linguist" or from the terminal with "linguist".
(4) Translate all texts (this should be self explaining, but do not manipulate things like "%s" or "{0}")
(5) save the *.ts File locally and send it o me via email matthias.laumer@web.de 

I will include the language in the next release of webradio-py. 
If you do not want to wait, you can compile this by our own, locally at your machine. In order to do this:
(6) download ["translate.pro"](https://github.com/Acer54/Webradio_v2/raw/master/opt/webradio/locale/translate.pro)
(7) move and replace the downloaded file to /opt/webradio/locale/translate.pro
(8) move your translated locale_ro,ts file to the same folder
(9) compile translation from terminal (cd /opt/webradio/locale/ && lrelease translate.pro)
(10) restart webradio-py. Your new translation should be selectable in Settings-tab.

Regards,
Matthias

**Comment by omulverde** [comment]
I translate and I instaled RO. ScreenSAver is not translated. Have I do something special to work?

**Comment by Acer54** [comment]
What do you mean with "Screensacer is not translated" ? What would you translate? The Date?

**Comment by omulverde** [comment]
OK . I understand. I will change locale to romanian. Thanks. I thought it is from WebRadio. It is about the days of the week.

**Comment by omulverde** [comment]
In local_ro.ts I do not find world "on AIR".

**Comment by Acer54** [comment]
"on Air" is not made to be translated ... this is the same in every langage ;-)

**Comment by omulverde** [comment]
OK, I do not insist...

**Comment by omulverde** [comment]
I translated to romanian. I installed files but on I push "MP3 PLayer" section, aplication freeze. What is wrong?

**Comment by Acer54** [comment]
Have you reviewed the Log-File in /home/pi/.webradio/webradio.log ? Maybe there eas an uncaught exception...

**Comment by omulverde** [comment]
Here is the logs. Maybe you descover what is the problem with freeze Pi. Some coments where I think the problem is.

2019-12-03 06:43:32,094 - WARNING - lib.googleapiclient.discovery_cache - MainT$
Traceback (most recent call last):
  File "/opt/webradio/lib/googleapiclient/discovery_cache/__init__.py", line 41$
    from . import file_cache
  File "/opt/webradio/lib/googleapiclient/discovery_cache/file_cache.py", line $
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2019-12-03 06:43:32,122 - WARNING - webradio - MainThread - Could not connect t$
2019-12-03 06:43:33,221 - WARNING - lib.gpio_simulator - MainThread - Could not$
2019-12-03 06:43:33,222 - WARNING - lib.gpio_simulator - MainThread - Die VerzÃ$
2019-12-03 06:43:33,254 - WARNING - lib.gpio_watchdog - MainThread - Ein Rotary$
2019-12-03 06:43:33,256 - WARNING - root - MainThread - Adafruit DHT is not ins$
2019-12-03 06:43:33,263 - INFO - webradio - MainThread - Using MPD Music-Folder$
2019-12-03 06:43:33,537 - INFO - webradio - MainThread - eyed3 is available, us$

2019-12-03 06:43:37,759 - WARNING - webradio - MainThread - Some Network connec$
2019-12-03 06:47:09,118 - ERROR - webradio - MainThread - Uncaught exception
Traceback (most recent call last):
  File "/opt/webradio/webradio.py", line 2848, in RLCD_off
    self.gpio_watchdog.set_output_HIGH(self.get_save_value_from_globals_configu$
AttributeError: 'MainWindow' object has no attribute 'gpio_watchdog'
2019-12-03 06:48:53,721 - WARNING - webradio - MainThread - Re-Check
2019-12-03 06:48:55,289 - INFO - webradio - MainThread - Network Connection eta$
2019-12-03 06:48:55,428 - WARNING - webradio - MainThread - Disable Youtube-Sea$
2019-12-03 06:48:55,692 - INFO - webradio - MainThread - Loading Stylesheet: /o$

Traceback (most recent call last):
  File "/opt/webradio/lib/googleapiclient/discovery_cache/__init__.py", line 41$
    from . import file_cache
  File "/opt/webradio/lib/googleapiclient/discovery_cache/file_cache.py", line $
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0

2019-12-03 07:03:51,069 - INFO - webradio - MainThread - Running with Screen-Re$
2019-12-03 07:03:51,718 - WARNING - lib.googleapiclient.discovery_cache - MainT$
Traceback (most recent call last):
  File "/opt/webradio/lib/googleapiclient/discovery_cache/__init__.py", line 41$
    from . import file_cache
  File "/opt/webradio/lib/googleapiclient/discovery_cache/file_cache.py", line $
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2019-12-03 07:03:51,731 - WARNING - webradio - MainThread - Could not connect t$
2019-12-03 07:03:52,750 - WARNING - lib.gpio_simulator - MainThread - Could not$
2019-12-03 07:03:52,753 - WARNING - lib.gpio_simulator - MainThread - Die VerzÃ$
2019-12-03 07:03:52,777 - WARNING - lib.gpio_watchdog - MainThread - Ein Rotary$
2019-12-03 07:03:52,780 - WARNING - root - MainThread - Adafruit DHT is not ins$
2019-12-03 07:03:52,789 - INFO - webradio - MainThread - Using MPD Music-Folder$

**Comment by omulverde** [comment]
The same error apears every time when freeze.

2019-12-03 17:57:13,665 - WARNING - lib.googleapiclient.discovery_cache - MainT$
Traceback (most recent call last):
  File "/opt/webradio/lib/googleapiclient/discovery_cache/__init__.py", line 41$
    from . import file_cache
  File "/opt/webradio/lib/googleapiclient/discovery_cache/file_cache.py", line $
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2019-12-03 17:57:13,680 - WARNING - webradio - MainThread - Could not connect t$
2019-12-03 17:57:14,751 - WARNING - lib.gpio_simulator - MainThread - Could not$
2019-12-03 17:57:14,752 - WARNING - lib.gpio_simulator - MainThread - Die VerzÃ$
2019-12-03 17:57:14,840 - WARNING - lib.gpio_watchdog - MainThread - Ein Rotary$
2019-12-03 17:57:14,845 - WARNING - root - MainThread - Adafruit DHT is not ins$
2019-12-03 17:57:19,303 - INFO - webradio - MainThread - Checking Network
2019-12-03 17:57:19,309 - WARNING - webradio - MainThread - Some Network connec$
2019-12-03 18:17:07,459 - ERROR - webradio - MainThread - Uncaught exception
Traceback (most recent call last):
  File "/opt/webradio/webradio.py", line 2848, in RLCD_off
    self.gpio_watchdog.set_output_HIGH(self.get_save_value_from_globals_configu$
AttributeError: 'MainWindow' object has no attribute 'gpio_watchdog'
2019-12-03 18:21:56,994 - WARNING - webradio - MainThread - Re-Check
2019-12-03 18:21:59,998 - INFO - webradio - MainThread - Network Connection eta$
2019-12-03 18:22:00,132 - WARNING - webradio - MainThread - Disable Youtube-Sea$
2019-12-03 18:22:00,286 - INFO - webradio - MainThread - Loading Stylesheet: /o$
2019-12-03 18:59:30,399 - ERROR - webradio - MainThread - Uncaught exception
Traceback (most recent call last):
  File "/opt/webradio/webradio.py", line 4350, in <module>
    mainwindow.startup_actions()
  File "/opt/webradio/webradio.py", line 1040, in startup_actions
    self.checkInternet()
  File "/opt/webradio/webradio.py", line 1223, in checkInternet
    status_ok, results = systemtest()
  File "/opt/webradio/lib/system_test.py", line 44, in test_onlineServices
    urllib2.urlopen(LASTFM, timeout=3)  #seems like this server is sometimes sl$
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)

**Comment by Acer54** [comment]
You can ignore Error "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0" ... this does not harm and is normal with this version.

What is confusing, are the errors because of the GPIO-Watchdog?? This should not happen.

The third error I see is because of (during startup) webradio is not able to connect to a Server (LastFM)... this might be because of a bad internet connection? Have you still set your pi to "wait for network" as a Bootoption (via raspi-config)?

In general, all of the log-lines are cut off ... can you attach the logfile as a "file"? Containing the whole output?

**Comment by omulverde** [comment]
1. Yes, I set wait for network
2. I made a lot of tests yesterday and log file is big. I will send to you this evening
3. Also I will send file for (RO) but it is not finished because the section "MP3 Player" freeze and it is not tested. This misfunctionality appears after compile file for "ro" (I suspect that). Before worked fine.

**Comment by Acer54** [comment]
Just send the files to my mail-adr. I´ll test the translations at my machine to see if there was something wrong wich might cause this problem.

By the way: During your "playtime" yesterday ... have you added a lot of "youtube-tracks" to your Media-Player-Playlist ?? These links are refreshed initially and we have learned that this process is horribly slow at the moment (dont know why, maybe in connection with the servers of youtube...) maybe this would be the problem?
If so, it should be solved when deleting ~/.webradio/yt-translations.tmp  (or something like this ... not sure about the correct filename). Of course this would only be a temporary workaround, but if the deletion of this file would work, we can point at the problem...

**Comment by omulverde** [comment]
Yes. You are right. I tested every kind of music, made search for a lot of keywords; now this section of software are freeze entirely WebRadio software and I have to restart by cutting the power. I will test when I arrive at home from the job. I will send .log file and I will delete the file .tmp or whatever will be.
Anyway, in that section there is not translation of any word, but inside the file ~ro.ts I made translation for that words (Previous, next, s.o.)

**Comment by Acer54** [comment]
I dont think that your translation causes trouble ... If something it translated in a wrong way it just gets ignored...
I fear that a bigger amount of youtube-tracks is getting updated which can cause the ui to freeze ... 
This got many reasons where I have to dig myself into it.

**Comment by omulverde** [comment]
The file I think is "tmp.trans.dmp". I seen have info about foto and info  about google. I will rename and restart Webradio. When you start WebRadio, delete it!

**Comment by omulverde** [comment]
YES!!!!!!!
I renamed file tmp.trans.dmp and surprize .... works!

**Comment by Acer54** [comment]
Ok, but of course this is a bug and should not happen... Will have a look into it.

**Comment by Acer54** [comment]
Found nothing suspicious in your logs. Maybe your Screensaver interval is a little bis short ... some "LCD-Off" commands fail ... but nothing critical.
I have tried to reproduce the issue with the youtube-link updates ... maybe there was a change in the past which I have missed or something is wrong with the updateprocedure where I have to work around.
Will check it.
We have something similar in the upcoming Python3 implementation... 

Expect an update on this not earlier than end of weekend ;-)

**Comment by omulverde** [comment]
OK. My opinion is that the better thing is when WebRadio starts write some cod to clear all unwanted temp file to avoid situation like mine. I have 2 Pi system; one is conected to tv (for radio; work 24h 7 days without problems; the same setings of screensaver -30sec). Only this (with logs for test on it) became creazy after search online on it. After delete the tmp file situation became normal. Conclusion: problem with tmp file. On the other side, the Pi conected on tv for radio has other problem; disipear status bar from all windows. Even I can not stop any aplication because do not have eny butons at windows. I will send adres to conect online to it to see; but work on radio 24 hours from 24

**Comment by Acer54** [comment]
I want to quote Bill Gates here: 

> Its a feature, not a bug!

Streaming-Links, provided by youtube, have only a little period of validity (1-2 days), this means, if you add a "youtube-title" to your media-playlist it just wont play if you try to start it a few days later... because of this, I have implemented a kind of update routine which is looking for outdated links and request a new one from the youtube-servers in order to be able to play that track if needed.
This takes a while per track (about 3-5 sek.) unfortunately, something seems to has changed in the last month (did not try it for a long time but also got no negative feedback from the users...) which causes strong delays and a freezing ui. 
Yesterday I have tried to debug this and found that this "update-process" might get started several times ... so if you had about 10 Online-Tracks in your playlist it will take up about 1 Minute to update it only once ... but the process might be startet serveral times (I saw about 4...) so in this case it will take at minimum 5 minutes (for 10 tracks)....  
If you want to use this functionality (online-tracks) with this version, I suggest a cronjob, running in the night to delete your tmp.trans.dmp.

Regards,
Matthias

**Comment by Acer54** [comment]
If you like, you can update your installation like descibed here: https://github.com/Acer54/Webradio_v2/issues/46
The "loading" problem should be solved with this (at least, it would not block the GUI thread for such a long time...)

**Comment by omulverde** [comment]
I tested. Working even in romanian. I seen the the world "Clock" desapier. A little bit stress test for Youtube streaming till tomorow. Yesterday my provider anounced me that I'm was attached by hackers on this Pi machine on ssh port (22). Do you want the log for your info? They do not guess the password for entire day. I'm happy; they are stupid chiness people. Disable ssh conect from Pi Configuration.

**Comment by omulverde** [comment]
At the wind section "ENE" can you put "E-NE". It is a little confusion for everybody.

**Comment by omulverde** [comment]
When you start WebRadio, in taskbar window is called "Form" not "WebRadio". Rain Probability is written with small fonts than other.

**Comment by Acer54** [comment]
Please start separate issues...
