### ISSUE TITLE
"ImportError: No module named QtWebKit" ab Rasbian Stretch (Debian8) 

### ISSUE THREAD

**Issue by Acer54** [Acer54/Webradio_v2#8]
Beim Start von webradio.py kommt es trotz korrekter Einrichtung und installation zu folgender Fehlermeldung:
```
pi@webradio:~ $ python ~/webradio/webradio.py --disable-gpio
Traceback (most recent call last):
  File "/home/pi/webradio/webradio.py", line 32, in 
    from lib.flickercharm import FlickCharm
  File "/home/pi/webradio/lib/flickercharm.py", line 11, in 
    from PyQt4.QtWebKit import *
ImportError: No module named QtWebKit
```
Das Modul libqtwebkit existiert nicht, trotz richtiger Installation aller notwendigen Abhängigkeiten

**Comment by Acer54** [comment]
Anpassung des Moduls flickercharm.py, so dass QtWrbkit nicht mehr verwendet wird. Release einer neuen Stable (0.3.1)
